// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// viterbi
RObject viterbi(NumericMatrix transProb, NumericMatrix emisProb, std::vector<double> initProb, std::vector<int> dataV);
RcppExport SEXP rspatiotemp_viterbi(SEXP transProbSEXP, SEXP emisProbSEXP, SEXP initProbSEXP, SEXP dataVSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type transProb(transProbSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type emisProb(emisProbSEXP);
    Rcpp::traits::input_parameter< std::vector<double> >::type initProb(initProbSEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type dataV(dataVSEXP);
    __result = Rcpp::wrap(viterbi(transProb, emisProb, initProb, dataV));
    return __result;
END_RCPP
}
