# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

convert <- function(data, groupSize, alphabetSize) {
    .Call('rspatiotemp_convert', PACKAGE = 'rspatiotemp', data, groupSize, alphabetSize)
}

createProbMatX <- function(dataO, dataH, groupSize, alphabetSizeO, alphabetSizeH) {
    .Call('rspatiotemp_createProbMatX', PACKAGE = 'rspatiotemp', dataO, dataH, groupSize, alphabetSizeO, alphabetSizeH)
}

updateProb <- function(prevData, dataO, dataH, groupSize, alphabetSizeO, alphabetSizeH) {
    .Call('rspatiotemp_updateProb', PACKAGE = 'rspatiotemp', prevData, dataO, dataH, groupSize, alphabetSizeO, alphabetSizeH)
}

forward <- function(transProb, emisProb, initProb, dataO, dataH, indexH) {
    .Call('rspatiotemp_forward', PACKAGE = 'rspatiotemp', transProb, emisProb, initProb, dataO, dataH, indexH)
}

forwardVec <- function(transProb, emisProb, initProb, dataO, dataH) {
    .Call('rspatiotemp_forwardVec', PACKAGE = 'rspatiotemp', transProb, emisProb, initProb, dataO, dataH)
}

viterbi <- function(transProb, emisProb, initProb, dataV) {
    .Call('rspatiotemp_viterbi', PACKAGE = 'rspatiotemp', transProb, emisProb, initProb, dataV)
}

train <- function(transProb, emisProb, initProb, dataV) {
    .Call('rspatiotemp_train', PACKAGE = 'rspatiotemp', transProb, emisProb, initProb, dataV)
}

